[package]
name = "mzspeclib-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "mzspeclib"

[dependencies]
indexmap = "2.11.0"
mzdata = "0.56.0"
mzpeaks = "1.0.9"
nom = "8.0.0"
nom-language = "0.1.0"
thiserror = "2.0.16"
